Skipping module archetype-resources due to failure.
Combined dot saved for repo: cloudera__flink-tutorials
Generating dot file for repo: xebialabs__overthere
Combined dot saved for repo: xebialabs__overthere
Generating dot file for repo: Plugily-Projects__MurderMystery
Combined dot saved for repo: Plugily-Projects__MurderMystery
Generating dot file for repo: dtprj__dongting
Combined dot saved for repo: dtprj__dongting
Generating dot file for repo: miltonio__milton2
Combined dot saved for repo: miltonio__milton2
Generating dot file for repo: NingNing0111__know-hub-ai
Error for project at C:\Users\akup390\Documents\repos\NingNing0111__know-hub-ai\know-hub-ai-core:

Skipping module know-hub-ai-core due to failure.
Error for project at C:\Users\akup390\Documents\repos\NingNing0111__know-hub-ai\know-hub-ai-system:

Skipping module know-hub-ai-system due to failure.
No successful modules for repo: NingNing0111__know-hub-ai
Generating dot file for repo: dougdonohoe__ddpoker
Traceback (most recent call last):
  File "C:\Users\akup390\Documents\tony-alvari-part4\part4-project\DependencyTreeAnalysis\generate_dot_file.py", line 80, in <module>
    generate_dot_file(repo, repo_path, dot_output_location, error_log_path)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akup390\Documents\tony-alvari-part4\part4-project\DependencyTreeAnalysis\generate_dot_file.py", line 25, in generate_dot_file
    combine_dot_files(temp_dot_files, combined_path)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akup390\Documents\tony-alvari-part4\part4-project\DependencyTreeAnalysis\generate_dot_file.py", line 53, in combine_dot_files
    with open(path, 'r') as infile:
         ~~~~^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\akup390\\Documents\\dot_files\\common_temp_0.dot'